config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord 
     belongs_to :user

     has_many :article_categories 
     has_many :categories, through: :article_categories
     
     validates :title, presence: true, length: {minimum:6, maximum:100}
     validates :description, presence: true, length: {minimum:10, maximum:300}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord 
    belongs_to :article 
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord 
    has_many :article_categories
    has_many :articles, through: :article_categories
    
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord 
    before_save {self.email = email.downcase}
    has_many :articles, dependent: :destroy
    has_secure_password

    validates :username, presence: true,uniqueness: {case_sensitive: false},  length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105}, format: {with: VALID_EMAIL_REGEX}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   
    helper_method :current_user, :logged_in?, :require_user
    
   def current_user 
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
   end

   def logged_in?
      !!current_user #!! turns current user into a boolean value
   end

   def require_user 
      if !logged_in?
         flash[:alert] = "You must be logged in"
      else
         redirect_to login_path
      end
   end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
before_action :set_article, only:[:show, :edit, :update, :destroy]
#before_action :require_user, except: [:show, :index] #you have to be logged in to create a new article
# before_action :require_same_user, except: [:edit, :update, :destroy] 
    
    def show
    end
    
    def index 
        @articles = Article.paginate(page: params[:page], per_page: 2)

    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was successfully created"
            redirect_to @article
        else 
            render "new", status: :unprocessable_entity 
        end
    end

    def edit 
    end

    def update 
        if @article.update(article_params)
            flash[:notice] = "Article has been updated"
            redirect_to @article
        else 
            render "edit"
        end
    end

    def destroy 
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article=Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, :category_ids:[])
    end

    # def require_same_user 
    #     if current_user != @article.user
    #         flash[:alert] = "You can only edit or delete your article"
    #         redirect_to @article
    #     end
    # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController 
    before_action :require_admin, except: [:index, :show]
    def new
        @category = Category.new
    end

    def index 
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    
    def show 
        @category = Category.find(params[:id])
        # @categories = @category.articles.paginate(page: params[:page], per_page: 5)

    end

    def create 
        @category = Category.new(category_params)
        if @category.save 
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render "new"
        end
    end

    def edit
        @category = Category.find(params[:id])
      end

      def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
          flash[:notice] = "Category name updated successfully"
          redirect_to @category
        else
          render 'edit'
        end
      end

    private 

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
          flash[:alert] = "Only admins can perform that action"
          redirect_to categories_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
       user = User.find_by(email:params[:session][:email].downcase)
       if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id # user authenticated and stays logged in 
            flash[:notice] ="Login successful"
            redirect_to user
       else
            flash.now[:alert] = "There was something wrong with your login"
            render 'new', status: :unprocessable_entity 
       end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to login_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :require_user, only: [:show,:edit, :update, :destroy]
    #before_action :require_same_user, only: [:show,:edit, :update, :destroy]

    def new
        @user = User.new
    end

    def index 
        @users= User.all
    end

    def show 
        @user = User.find(params[:id])
        @articles= @user.articles
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}"
            redirect_to articles_path
        else 
            render 'new', status: :unprocessable_entity 
        end
    end

    def edit 
        @user = User.find(params[:id])
    end

    def update 
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "User updated successfully"
        else
            render 'edit'
        end
    end

    def destroy
        @user=User.find(params[:id])
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "User deleted successfully"
        redirect_to articles_path
    end
    private 

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def require_same_user
        if current_user != @user
            flash[:alert] = "You have to be logged in"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = {size:80})
        email_address= user.email.downcase
        hash= Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username)
    end



end

app/views/articles/_article.html.erb
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan='3'>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article|%>
       
        <tr>
            <td><%= article.title%></td>
            <td><%= article.description%>  </td>
            <td><%=link_to "Show", article_path(article) %></td>
            <% if logged_in? && article.user == current_user%>
                <td><%=link_to "Edit", edit_article_path(article) %></td>
                <td><%=link_to 'Delete', article_path(article), data:{"turbo-method": :delete}%>  by <%=article.user.username if article.user%> </td>  
            <%end%>
        </tr>
        <%end%>
    </tbody>
</table>

<p>
    <%= link_to 'Create new article', new_article_path%>
</p>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            {prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %> 
           </div>
        </div> 

        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<% if @article.errors.any?%>
<h2>The following errors prevented the article from being saved</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg|%>
            <li><%=msg%></li>
        <%end%>
    </ul>
<%end%>
<%= form_with(model: @article, local: true) do |f|%>
    <p>
        <%= f.label :title%><br>
        <%= f.text_field :title%>
    </p>

      <p>
        <%= f.label :description%><br>
        <%= f.text_area :description%>
    </p>

      <p>
        <%= f.submit%>
    </p>

<%end%>
<%= link_to 'Cancel and return to articles listing', articles_path%>

app/views/articles/index.html.erb
  <h1>Articles Listing Page</h1>

  <div class="apple_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>


  <%= render 'article'%>

  <div class="apple_pagination">
      <%= will_paginate @articles, :container => false %>
    </div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description:</strong><%= @article.description %></p>
by <%= "(Admin)" if current_user.admin?%> <%=@article.user.username if @article.user %> <br><br>
<%= link_to gravatar_for(@article.user), user_path(@article.user)%>

<%if logged_in? && @article.user == current_user%>
    <%= link_to 'Edit', edit_article_path(@article)%> |
    <%= link_to 'Delete', article_path(@article), data:{"turbo-method": :delete}%> | 
<%end%>
    <%= link_to 'Return to articles listing', articles_path%>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <%# <p class="card-text"><%= pluralize(category.articles.count, "article") %></p> %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1>Create a new category</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>


        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name%>Category</h1>

app/views/layouts/_messages.html.erb
    <% flash.each do |name, msg|%>
      <%=msg%>
    <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%=render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <%# <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div> %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Alpha Blogers</h1>

<table>
    <thead>
        <tr>
            <th>User</th>
            <th>Email</th>
            <th colspan='3'>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @users.each do |user|%>
       
        <tr>
            <td><%= link_to user.username, user%></td>
            <td><%= user.email%>  </td>
            <td><%= pluralize(user.articles.count, "article")%>  </td>
            <td><%=link_to "Show", user_path(user) %></td>
            <%if logged_in?%>
                <% if user == current_user %>
                    <td><%=link_to "Edit Profile", edit_user_path(user) %></td>
                <%end%>
                <%if current_user.admin?%>
                    <td><%=link_to 'Delete', user_path(user), data:{"turbo-method": :delete}%>  </td>  
                <%end%>
             <%end%>
       </tr>
        <%end%>
    </tbody>
</table>

<p>
    <%= link_to 'Create new article', new_article_path%>
</p>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username%>'s profile</h1>

<%= gravatar_for @user, size: 200%> <br>
<%= link_to 'Logout', logout_path, data:{"turbo-method": :delete}%>
<%= link_to 'Delete Profile', user_path(current_user), data:{"turbo-method": :delete} %>

<h3><%=@user.username%>'s profile</h3>

<%=render 'articles/article'%>